from __future__ import annotations

import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]

EXPECTED_LINK_COUNTS = [
    ("docs-main/overview/reference/canton-coin-tokenomics.mdx", "Scan State API", "/sdks-tools/api-reference/splice-scan-current-state-api", 1),
    ("docs-main/overview/reference/canton-coin-tokenomics.mdx", "minting delegation", "/global-synchronizer/splice-fundamentals/rewards-minting", 1),
    ("docs-main/appdev/modules/m4-featured-app-activity-marker.mdx", "types_of_activity_records", "/overview/reference/canton-coin-tokenomics", 1),
    ("docs-main/appdev/modules/m7-canton-coin-preapprovals.mdx", "API docs", "/sdks-tools/api-reference/splice-validator-api", 1),
    ("docs-main/appdev/modules/m7-canton-coin-preapprovals.mdx", "limit on the number of parties", "/global-synchronizer/production-operations/scalability", 1),
    ("docs-main/global-synchronizer/deployment/community-docker-compose-helm.mdx", "Docker Compose-Based Deployment of a Validator Node", "/global-synchronizer/deployment/validator-docker-compose", 1),
    ("docs-main/global-synchronizer/deployment/community-helm-templating.mdx", "Kubernetes-Based Deployment of a Super Validator node", "/global-synchronizer/deployment/kubernetes-deployment", 1),
    ("docs-main/global-synchronizer/deployment/community-helm-templating.mdx", "Kubernetes-Based Deployment of a Validator node", "/global-synchronizer/deployment/validator-kubernetes", 1),
    ("docs-main/global-synchronizer/deployment/community-keycloak-config.mdx", "Configuring Authentication", "/global-synchronizer/deployment/validator-kubernetes", 1),
    ("docs-main/global-synchronizer/deployment/kubernetes-deployment.mdx", "Canton console", "/global-synchronizer/canton-console/essential-commands", 1),
    ("docs-main/global-synchronizer/deployment/kubernetes-deployment.mdx", "config override", "/global-synchronizer/deployment/configuration", 1),
    ("docs-main/global-synchronizer/deployment/kubernetes-deployment.mdx", "configure pruning", "/global-synchronizer/production-operations/sv-pruning", 1),
    ("docs-main/global-synchronizer/deployment/kubernetes-deployment.mdx", "environment variables", "/global-synchronizer/deployment/configuration", 1),
    ("docs-main/global-synchronizer/deployment/kubernetes-deployment.mdx", "logical synchronizer upgrade", "/global-synchronizer/production-operations/logical-synchronizer-upgrade", 1),
    ("docs-main/snippets/networkvars/global-synchronizer/deployment/kubernetes-deployment-1.mdx", "logical synchronizer upgrade", "/global-synchronizer/production-operations/logical-synchronizer-upgrade", 1),
    ("docs-main/snippets/networkvars/global-synchronizer/deployment/kubernetes-deployment-4.mdx", "configure pruning", "/global-synchronizer/production-operations/sv-pruning", 1),
    ("docs-main/global-synchronizer/deployment/onboarding-process.mdx", "validator helm chart configuration", "/global-synchronizer/deployment/validator-kubernetes", 1),
    ("docs-main/snippets/networkvars/global-synchronizer/deployment/onboarding-process-1.mdx", "validator helm chart configuration", "/global-synchronizer/deployment/validator-kubernetes", 1),
    ("docs-main/global-synchronizer/deployment/sv-operations.mdx", "Cache mechanism", "/global-synchronizer/deployment/sv-operations", 1),
    ("docs-main/global-synchronizer/deployment/sv-operations.mdx", "cometbft-identity", "/global-synchronizer/deployment/kubernetes-deployment", 1),
    ("docs-main/global-synchronizer/deployment/sv-operations.mdx", "constructs a party exclusion config", "/global-synchronizer/deployment/sv-operations", 1),
    ("docs-main/global-synchronizer/deployment/sv-operations.mdx", "login into the SV web UI", "/global-synchronizer/deployment/kubernetes-deployment", 1),
    ("docs-main/global-synchronizer/deployment/sv-operations.mdx", "sv-helm", "/global-synchronizer/deployment/kubernetes-deployment", 1),
    ("docs-main/global-synchronizer/deployment/sv-operations.mdx", "sv-identity", "/global-synchronizer/deployment/kubernetes-deployment", 1),
    ("docs-main/global-synchronizer/deployment/sv-operations.mdx", "sv-security", "/global-synchronizer/production-operations/sv-security", 1),
    ("docs-main/global-synchronizer/deployment/sv-operations.mdx", "synchronizer traffic parameters", "/global-synchronizer/deployment/synchronizer-traffic", 1),
    ("docs-main/global-synchronizer/deployment/sv-operations.mdx", "this instruction to prepare for validator onboarding", "/global-synchronizer/deployment/validator-kubernetes", 1),
    ("docs-main/global-synchronizer/deployment/sv-operations.mdx", "traffic consumption", "/global-synchronizer/deployment/synchronizer-traffic", 1),
    ("docs-main/global-synchronizer/deployment/synchronizer-traffic.mdx", "Docker-compose one", "/global-synchronizer/deployment/validator-docker-compose", 1),
    ("docs-main/global-synchronizer/deployment/synchronizer-traffic.mdx", "Grafana dashboard", "/global-synchronizer/production-operations/splice-metrics-overview", 1),
    ("docs-main/global-synchronizer/deployment/synchronizer-traffic.mdx", "Kubernetes validator deployment guide", "/global-synchronizer/deployment/validator-kubernetes", 1),
    ("docs-main/global-synchronizer/deployment/synchronizer-traffic.mdx", "SV operations docs", "/global-synchronizer/deployment/sv-operations", 1),
    ("docs-main/global-synchronizer/deployment/synchronizer-traffic.mdx", "abort ledger submissions", "/global-synchronizer/troubleshooting-guide/troubleshooting-methodology", 1),
    ("docs-main/global-synchronizer/deployment/synchronizer-traffic.mdx", "abort ledger submissions if the balance has fallen below a predefined amount", "/global-synchronizer/troubleshooting-guide/troubleshooting-methodology", 1),
    ("docs-main/global-synchronizer/deployment/synchronizer-traffic.mdx", "metrics", "/global-synchronizer/production-operations/splice-metrics-overview", 1),
    ("docs-main/snippets/networkvars/global-synchronizer/deployment/synchronizer-traffic-1.mdx", "SV operations docs", "/global-synchronizer/deployment/sv-operations", 1),
    ("docs-main/global-synchronizer/deployment/validator-docker-compose.mdx", "Users, Parties and Wallets in the Splice Wallet section", "/global-synchronizer/deployment/validator-users", 1),
    ("docs-main/global-synchronizer/deployment/validator-docker-compose.mdx", "authentication section", "/global-synchronizer/deployment/validator-kubernetes", 1),
    ("docs-main/global-synchronizer/deployment/validator-docker-compose.mdx", "automatically purchase traffic", "/global-synchronizer/deployment/synchronizer-traffic", 1),
    ("docs-main/global-synchronizer/deployment/validator-docker-compose.mdx", "traffic", "/global-synchronizer/deployment/synchronizer-traffic", 1),
    ("docs-main/global-synchronizer/deployment/validator-kubernetes.mdx", "Disaster Recovery", "/global-synchronizer/production-operations/validator-disaster-recovery", 1),
    ("docs-main/global-synchronizer/deployment/validator-kubernetes.mdx", "automatically purchase traffic", "/global-synchronizer/deployment/synchronizer-traffic", 1),
    ("docs-main/global-synchronizer/deployment/validator-kubernetes.mdx", "error-insufficient-funds", "/global-synchronizer/troubleshooting-guide/troubleshooting-methodology", 1),
    ("docs-main/global-synchronizer/deployment/validator-kubernetes.mdx", "traffic", "/global-synchronizer/deployment/synchronizer-traffic", 1),
    ("docs-main/global-synchronizer/deployment/validator-networking.mdx", "the network diagram", "/global-synchronizer/deployment/validator-kubernetes", 1),
    ("docs-main/global-synchronizer/deployment/validator-users.mdx", "helm_validator_topup", "/global-synchronizer/deployment/validator-kubernetes", 1),
    ("docs-main/global-synchronizer/faq.mdx", "Adding ad-hoc configuration", "/global-synchronizer/deployment/configuration", 1),
    ("docs-main/global-synchronizer/faq.mdx", "generate a validator onboarding token", "/global-synchronizer/deployment/sv-operations", 1),
    ("docs-main/global-synchronizer/faq.mdx", "lnav", "/global-synchronizer/troubleshooting-guide/troubleshooting-methodology", 1),
    ("docs-main/global-synchronizer/production-operations/disaster-recovery.mdx", "Backup of Node Identities", "/global-synchronizer/production-operations/sv-backup", 1),
    ("docs-main/global-synchronizer/production-operations/disaster-recovery.mdx", "Restore from backup", "/global-synchronizer/production-operations/disaster-recovery", 1),
    ("docs-main/global-synchronizer/production-operations/disaster-recovery.mdx", "Restoring from a Participant Identities Dump", "/global-synchronizer/production-operations/validator-disaster-recovery", 1),
    ("docs-main/global-synchronizer/production-operations/disaster-recovery.mdx", "helm-sv-install", "/global-synchronizer/deployment/kubernetes-deployment", 1),
    ("docs-main/global-synchronizer/production-operations/disaster-recovery.mdx", "helm-validator-auth0", "/global-synchronizer/deployment/validator-kubernetes", 1),
    ("docs-main/global-synchronizer/production-operations/disaster-recovery.mdx", "helm-validator-install", "/global-synchronizer/deployment/validator-kubernetes", 1),
    ("docs-main/global-synchronizer/production-operations/disaster-recovery.mdx", "logical synchronizer upgrade", "/global-synchronizer/production-operations/logical-synchronizer-upgrade", 1),
    ("docs-main/global-synchronizer/production-operations/disaster-recovery.mdx", "recovered", "/global-synchronizer/production-operations/disaster-recovery", 1),
    ("docs-main/global-synchronizer/production-operations/disaster-recovery.mdx", "sv_backups", "/global-synchronizer/production-operations/sv-backup", 1),
    ("docs-main/global-synchronizer/production-operations/logical-synchronizer-upgrade.mdx", "procedure", "/global-synchronizer/production-operations/validator-disaster-recovery", 1),
    ("docs-main/global-synchronizer/production-operations/logical-synchronizer-upgrade.mdx", "validators", "/global-synchronizer/production-operations/validator-disaster-recovery", 1),
    ("docs-main/global-synchronizer/production-operations/scalability.mdx", "docs", "/appdev/modules/m7-canton-coin-preapprovals", 1),
    ("docs-main/global-synchronizer/production-operations/scalability.mdx", "environment variables", "/global-synchronizer/deployment/configuration", 1),
    ("docs-main/global-synchronizer/production-operations/scalability.mdx", "minting delegation", "/global-synchronizer/splice-fundamentals/rewards-minting", 1),
    ("docs-main/global-synchronizer/production-operations/scalability.mdx", "token standard", "/appdev/deep-dives/token-standard", 1),
    ("docs-main/global-synchronizer/production-operations/splice-metrics-overview.mdx", "Adding ad-hoc configuration", "/global-synchronizer/deployment/configuration", 1),
    ("docs-main/global-synchronizer/production-operations/splice-metrics-overview.mdx", "metrics reference", "/global-synchronizer/reference/metrics-reference", 1),
    ("docs-main/global-synchronizer/production-operations/splice-metrics-overview.mdx", "validator-metrics-reference", "/global-synchronizer/reference/metrics-reference", 1),
    ("docs-main/global-synchronizer/production-operations/sv-backup.mdx", "logical synchronizer upgrades", "/global-synchronizer/production-operations/logical-synchronizer-upgrade", 1),
    ("docs-main/global-synchronizer/production-operations/sv-backup.mdx", "pruning", "/global-synchronizer/production-operations/sv-pruning", 2),
    ("docs-main/global-synchronizer/production-operations/sv-security.mdx", "above", "/global-synchronizer/production-operations/sv-security", 1),
    ("docs-main/global-synchronizer/production-operations/sv-security.mdx", "change the way in which your CometBFT governance key is managed", "/global-synchronizer/production-operations/sv-security", 1),
    ("docs-main/global-synchronizer/production-operations/sv-security.mdx", "changes to the SV app deployment", "/global-synchronizer/production-operations/sv-security", 1),
    ("docs-main/global-synchronizer/production-operations/sv-security.mdx", "configuration changes to the participant Helm chart", "/global-synchronizer/production-operations/sv-security", 1),
    ("docs-main/global-synchronizer/production-operations/sv-security.mdx", "setup of a validator participant with KMS", "/global-synchronizer/production-operations/validator-security", 1),
    ("docs-main/global-synchronizer/production-operations/sv-security.mdx", "sv-helm", "/global-synchronizer/deployment/kubernetes-deployment", 1),
    ("docs-main/global-synchronizer/production-operations/validator-backups.mdx", "logical synchronizer upgrades", "/global-synchronizer/production-operations/logical-synchronizer-upgrade", 1),
    ("docs-main/global-synchronizer/production-operations/validator-backups.mdx", "pruning", "/global-synchronizer/deployment/validator-kubernetes", 1),
    ("docs-main/global-synchronizer/production-operations/validator-backups.mdx", "use an external KMS", "/global-synchronizer/production-operations/validator-security", 1),
    ("docs-main/global-synchronizer/production-operations/validator-disaster-recovery.mdx", "Backup of Node Identities", "/global-synchronizer/production-operations/validator-backups", 1),
    ("docs-main/global-synchronizer/production-operations/validator-disaster-recovery.mdx", "Canton console", "/global-synchronizer/canton-console/essential-commands", 1),
    ("docs-main/global-synchronizer/production-operations/validator-disaster-recovery.mdx", "additional configuration", "/global-synchronizer/deployment/configuration", 1),
    ("docs-main/global-synchronizer/production-operations/validator-disaster-recovery.mdx", "configuration option", "/global-synchronizer/deployment/configuration", 1),
    ("docs-main/global-synchronizer/production-operations/validator-disaster-recovery.mdx", "database backup", "/global-synchronizer/production-operations/validator-backups", 1),
    ("docs-main/global-synchronizer/production-operations/validator-disaster-recovery.mdx", "docs for the validator external signing API", "/sdks-tools/api-reference/splice-validator-api", 1),
    ("docs-main/global-synchronizer/production-operations/validator-disaster-recovery.mdx", "external KMS", "/global-synchronizer/production-operations/validator-security", 1),
    ("docs-main/global-synchronizer/production-operations/validator-disaster-recovery.mdx", "helm-validator-install", "/global-synchronizer/deployment/validator-kubernetes", 1),
    ("docs-main/global-synchronizer/production-operations/validator-disaster-recovery.mdx", "identities backup", "/global-synchronizer/production-operations/validator-backups", 1),
    ("docs-main/global-synchronizer/production-operations/validator-disaster-recovery.mdx", "logical synchronizer upgrade", "/global-synchronizer/production-operations/logical-synchronizer-upgrade", 1),
    ("docs-main/global-synchronizer/production-operations/validator-disaster-recovery.mdx", "participant console", "/global-synchronizer/canton-console/essential-commands", 1),
    ("docs-main/snippets/networkvars/global-synchronizer/production-operations/validator-disaster-recovery-1.mdx", "participant console", "/global-synchronizer/canton-console/essential-commands", 1),
    ("docs-main/snippets/networkvars/global-synchronizer/production-operations/validator-disaster-recovery-2.mdx", "docs for the validator external signing API", "/sdks-tools/api-reference/splice-validator-api", 1),
    ("docs-main/global-synchronizer/production-operations/validator-security.mdx", "Docker Compose-based deployments", "/global-synchronizer/deployment/validator-docker-compose", 1),
    ("docs-main/global-synchronizer/production-operations/validator-security.mdx", "Helm-based deployment", "/global-synchronizer/deployment/validator-kubernetes", 1),
    ("docs-main/global-synchronizer/production-operations/validator-security.mdx", "above", "/global-synchronizer/production-operations/validator-security", 1),
    ("docs-main/global-synchronizer/reference/metrics-reference.mdx", "Metrics", "/global-synchronizer/production-operations/splice-metrics-overview", 1),
    ("docs-main/global-synchronizer/splice-fundamentals/glossary.mdx", "traffic", "/global-synchronizer/deployment/synchronizer-traffic", 1),
    ("docs-main/global-synchronizer/splice-fundamentals/rewards-minting.mdx", "max 200 Splice wallet parties limit", "/global-synchronizer/production-operations/scalability", 1),
    ("docs-main/global-synchronizer/troubleshooting-guide/troubleshooting-methodology.mdx", "purchase any traffic", "/global-synchronizer/deployment/synchronizer-traffic", 1),
    ("docs-main/global-synchronizer/troubleshooting-guide/troubleshooting-methodology.mdx", "purchase traffic", "/global-synchronizer/deployment/synchronizer-traffic", 1),
    ("docs-main/global-synchronizer/troubleshooting-guide/troubleshooting-methodology.mdx", "validator_reonboard", "/global-synchronizer/production-operations/validator-disaster-recovery", 1),
    ("docs-main/overview/reference/canton-coin-tokenomics.mdx", "Scan State API", "/sdks-tools/api-reference/splice-scan-current-state-api", 1),
    ("docs-main/overview/reference/canton-coin-tokenomics.mdx", "minting delegation", "/global-synchronizer/splice-fundamentals/rewards-minting", 1),
    ("docs-main/sdks-tools/api-reference/splice-architecture.mdx", "app_dev_daml_api", "/sdks-tools/api-reference/splice-daml-apis", 1),
    ("docs-main/sdks-tools/api-reference/splice-daml-apis.mdx", "Canton Coin transfer preapproval", "/appdev/modules/m7-canton-coin-preapprovals", 1),
    ("docs-main/sdks-tools/api-reference/splice-daml-apis.mdx", "featured wallet provider party", "/overview/reference/canton-coin-tokenomics", 1),
    ("docs-main/sdks-tools/api-reference/splice-daml-apis.mdx", "how_to_become_a_featured_application", "/overview/reference/canton-coin-tokenomics", 1),
    ("docs-main/snippets/networkvars/sdks-tools/api-reference/splice-daml-apis-1.mdx", "how_to_become_a_featured_application", "/overview/reference/canton-coin-tokenomics", 1),
    ("docs-main/sdks-tools/api-reference/splice-http-apis.mdx", "app_dev_scan_api", "/sdks-tools/api-reference/splice-scan-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-http-apis.mdx", "app_dev_validator_api", "/sdks-tools/api-reference/splice-validator-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-overview.mdx", "Canton Network Token Standard", "/sdks-tools/api-reference/splice-daml-apis", 1),
    ("docs-main/sdks-tools/api-reference/splice-overview.mdx", "app_dev_daml_api", "/sdks-tools/api-reference/splice-daml-apis", 1),
    ("docs-main/sdks-tools/api-reference/splice-overview.mdx", "app_dev_daml_models", "/sdks-tools/api-reference/splice-daml-models", 1),
    ("docs-main/sdks-tools/api-reference/splice-overview.mdx", "app_dev_scan_api", "/sdks-tools/api-reference/splice-scan-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-overview.mdx", "app_dev_validator_api", "/sdks-tools/api-reference/splice-validator-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-aggregates-api.mdx", "scan_bulk_data_api", "/sdks-tools/api-reference/splice-scan-bulk-data-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-aggregates-api.mdx", "v0_state_acs", "/sdks-tools/api-reference/splice-scan-bulk-data-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-aggregates-api.mdx", "v0_state_acs_snapshot-timestamp", "/sdks-tools/api-reference/splice-scan-bulk-data-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "app_dev_openapi_conventions", "/sdks-tools/api-reference/splice-http-apis", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "scan_aggregates_api", "/sdks-tools/api-reference/splice-scan-aggregates-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "scan_bulk_data_api", "/sdks-tools/api-reference/splice-scan-bulk-data-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "scan_cc_reference_data_api", "/sdks-tools/api-reference/splice-scan-cc-reference-data-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "scan_current_state_api", "/sdks-tools/api-reference/splice-scan-current-state-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "scan_global_synchronizer_connectivity_api", "/sdks-tools/api-reference/splice-scan-gs-connectivity-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "scan_global_synchronizer_operations_api", "/sdks-tools/api-reference/splice-scan-gs-operations-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "scan_openapi", "/sdks-tools/api-reference/splice-apis", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "validator-api-scan-proxy", "/sdks-tools/api-reference/splice-validator-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-bulk-data-api.mdx", "Listing_all_SV_Sequencers", "/sdks-tools/api-reference/splice-scan-gs-connectivity-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-bulk-data-api.mdx", "scan_openapi", "/sdks-tools/api-reference/splice-apis", 1),
    ("docs-main/snippets/networkvars/sdks-tools/api-reference/splice-scan-bulk-data-api-1.mdx", "scan_openapi", "/sdks-tools/api-reference/splice-apis", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-cc-reference-data-api.mdx", "scan_current_state_api", "/sdks-tools/api-reference/splice-scan-current-state-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-current-state-api.mdx", "overall Splice network operations", "/sdks-tools/api-reference/splice-scan-gs-operations-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-current-state-api.mdx", "traffic fees", "/global-synchronizer/deployment/synchronizer-traffic", 1),
    ("docs-main/sdks-tools/api-reference/splice-scan-gs-operations-api.mdx", "Listing_all_Validators", "/sdks-tools/api-reference/splice-scan-gs-connectivity-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "Canton Network Token Standard APIs", "/sdks-tools/api-reference/splice-daml-apis", 1),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "app-auth", "/sdks-tools/api-reference/splice-http-apis", 1),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "app_dev_openapi_conventions", "/sdks-tools/api-reference/splice-http-apis", 1),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "app_dev_scan_api", "/sdks-tools/api-reference/splice-scan-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "transfer offers", "/sdks-tools/api-reference/splice-validator-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "validator-api-ans", "/sdks-tools/api-reference/splice-validator-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "validator-api-external-signing", "/sdks-tools/api-reference/splice-validator-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "validator-api-internal", "/sdks-tools/api-reference/splice-validator-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "validator-api-scan-proxy", "/sdks-tools/api-reference/splice-validator-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "validator-api-user-management", "/sdks-tools/api-reference/splice-validator-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "validator-api-user-wallet", "/sdks-tools/api-reference/splice-validator-api", 1),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "validator-api-user-wallet-internal", "/sdks-tools/api-reference/splice-validator-api", 1),
]

REMOVED_INLINE_CODE_REFERENCES = [
    ("docs-main/appdev/modules/m4-featured-app-activity-marker.mdx", "`types_of_activity_records`"),
    ("docs-main/global-synchronizer/deployment/sv-operations.mdx", "`cometbft-identity`"),
    ("docs-main/global-synchronizer/deployment/sv-operations.mdx", "`sv-helm`"),
    ("docs-main/global-synchronizer/deployment/sv-operations.mdx", "`sv-identity`"),
    ("docs-main/global-synchronizer/deployment/sv-operations.mdx", "`sv-security`"),
    ("docs-main/snippets/networkvars/sdks-tools/api-reference/splice-daml-apis-1.mdx", "`how_to_become_a_featured_application`"),
    ("docs-main/snippets/networkvars/sdks-tools/api-reference/splice-scan-bulk-data-api-1.mdx", "`scan_openapi`"),
    ("docs-main/global-synchronizer/deployment/validator-kubernetes.mdx", "`error-insufficient-funds`"),
    ("docs-main/global-synchronizer/deployment/validator-users.mdx", "`helm_validator_topup`"),
    ("docs-main/global-synchronizer/production-operations/disaster-recovery.mdx", "`Backup of Node Identities`"),
    ("docs-main/global-synchronizer/production-operations/disaster-recovery.mdx", "`helm-sv-install`"),
    ("docs-main/global-synchronizer/production-operations/disaster-recovery.mdx", "`helm-validator-auth0`"),
    ("docs-main/global-synchronizer/production-operations/disaster-recovery.mdx", "`helm-validator-install`"),
    ("docs-main/global-synchronizer/production-operations/disaster-recovery.mdx", "`sv_backups`"),
    ("docs-main/global-synchronizer/production-operations/splice-metrics-overview.mdx", "`validator-metrics-reference`"),
    ("docs-main/global-synchronizer/production-operations/sv-security.mdx", "`sv-helm`"),
    ("docs-main/global-synchronizer/production-operations/validator-disaster-recovery.mdx", "`helm-validator-install`"),
    ("docs-main/global-synchronizer/splice-fundamentals/glossary.mdx", "`traffic`"),
    ("docs-main/global-synchronizer/troubleshooting-guide/troubleshooting-methodology.mdx", "`validator_reonboard`"),
    ("docs-main/sdks-tools/api-reference/splice-architecture.mdx", "`app_dev_daml_api`"),
    ("docs-main/sdks-tools/api-reference/splice-daml-apis.mdx", "`featured wallet provider party`"),
    ("docs-main/sdks-tools/api-reference/splice-daml-apis.mdx", "`how_to_become_a_featured_application`"),
    ("docs-main/sdks-tools/api-reference/splice-http-apis.mdx", "`app_dev_scan_api`"),
    ("docs-main/sdks-tools/api-reference/splice-http-apis.mdx", "`app_dev_validator_api`"),
    ("docs-main/sdks-tools/api-reference/splice-overview.mdx", "`app_dev_daml_api`"),
    ("docs-main/sdks-tools/api-reference/splice-overview.mdx", "`app_dev_daml_models`"),
    ("docs-main/sdks-tools/api-reference/splice-overview.mdx", "`app_dev_scan_api`"),
    ("docs-main/sdks-tools/api-reference/splice-overview.mdx", "`app_dev_validator_api`"),
    ("docs-main/sdks-tools/api-reference/splice-scan-aggregates-api.mdx", "`scan_bulk_data_api`"),
    ("docs-main/sdks-tools/api-reference/splice-scan-aggregates-api.mdx", "`v0_state_acs_snapshot-timestamp`"),
    ("docs-main/sdks-tools/api-reference/splice-scan-aggregates-api.mdx", "`v0_state_acs`"),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "`app_dev_openapi_conventions`"),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "`scan_aggregates_api`"),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "`scan_bulk_data_api`"),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "`scan_cc_reference_data_api`"),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "`scan_current_state_api`"),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "`scan_global_synchronizer_connectivity_api`"),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "`scan_global_synchronizer_operations_api`"),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "`scan_openapi`"),
    ("docs-main/sdks-tools/api-reference/splice-scan-api.mdx", "`validator-api-scan-proxy`"),
    ("docs-main/sdks-tools/api-reference/splice-scan-bulk-data-api.mdx", "`Listing_all_SV_Sequencers`"),
    ("docs-main/sdks-tools/api-reference/splice-scan-bulk-data-api.mdx", "`scan_openapi`"),
    ("docs-main/sdks-tools/api-reference/splice-scan-cc-reference-data-api.mdx", "`scan_current_state_api`"),
    ("docs-main/sdks-tools/api-reference/splice-scan-gs-operations-api.mdx", "`Listing_all_Validators`"),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "`app-auth`"),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "`app_dev_openapi_conventions`"),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "`app_dev_scan_api`"),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "`validator-api-ans`"),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "`validator-api-external-signing`"),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "`validator-api-internal`"),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "`validator-api-scan-proxy`"),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "`validator-api-user-management`"),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "`validator-api-user-wallet-internal`"),
    ("docs-main/sdks-tools/api-reference/splice-validator-api.mdx", "`validator-api-user-wallet`"),
]


def test_splice_copied_internal_cross_references_are_markdown_links() -> None:
    for relative_path, text, route, expected_count in EXPECTED_LINK_COUNTS:
        page = REPO_ROOT / relative_path
        markdown_link = f"[{text}]({route})"
        actual_count = page.read_text(encoding="utf-8").count(markdown_link)
        assert actual_count >= expected_count, (
            f"{relative_path} should contain {expected_count} instance(s) of "
            f"{markdown_link!r}, found {actual_count}"
        )


def test_splice_copied_internal_cross_references_are_not_code_literals() -> None:
    for relative_path, bad_literal in REMOVED_INLINE_CODE_REFERENCES:
        page = REPO_ROOT / relative_path
        assert bad_literal not in page.read_text(encoding="utf-8")


def test_splice_copied_internal_cross_references_do_not_split_words() -> None:
    repaired_pages = {relative_path for relative_path, _text, _route, _count in EXPECTED_LINK_COUNTS}
    for relative_path in sorted(repaired_pages):
        page = REPO_ROOT / relative_path
        assert re.search(r"\w\[[^\]]+\]\(/", page.read_text(encoding="utf-8")) is None
