// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

package labelindex

import (
	"os"
	"path/filepath"
	"testing"
)

func TestBuild_BasicLabelToHeading(t *testing.T) {
	root := t.TempDir()
	writeRST(t, root, "a.rst", `.. _canton-getting-started:

Getting Started
===============

Some content.

.. _subsection:

A Subsection
------------
`)

	idx, err := Build(root)
	if err != nil {
		t.Fatalf("build: %v", err)
	}

	loc, ok := idx.Resolve("canton-getting-started", "")
	if !ok {
		t.Fatal("expected canton-getting-started to resolve")
	}
	if loc.Heading != "Getting Started" {
		t.Errorf("want heading 'Getting Started', got %q", loc.Heading)
	}

	loc, ok = idx.Resolve("subsection", "")
	if !ok {
		t.Fatal("expected subsection to resolve")
	}
	if loc.Heading != "A Subsection" {
		t.Errorf("want heading 'A Subsection', got %q", loc.Heading)
	}
}

func TestBuild_DuplicateLabelAcrossVersions(t *testing.T) {
	root := t.TempDir()
	writeRST(t, root, "canton/3.4/intro.rst", `.. _intro:

Introduction
============
`)
	writeRST(t, root, "canton/3.5/intro.rst", `.. _intro:

Introduction
============
`)

	idx, err := Build(root)
	if err != nil {
		t.Fatalf("build: %v", err)
	}

	// From a 3.5 source, we should resolve to the 3.5 location.
	loc, ok := idx.Resolve("intro", filepath.Join(root, "canton/3.5/foo.rst"))
	if !ok {
		t.Fatal("intro did not resolve")
	}
	if !contains(loc.RSTPath, "3.5") {
		t.Errorf("want 3.5 location, got %s", loc.RSTPath)
	}

	// From a 3.4 source, we should prefer the 3.4 location.
	loc, ok = idx.Resolve("intro", filepath.Join(root, "canton/3.4/foo.rst"))
	if !ok {
		t.Fatal("intro did not resolve")
	}
	if !contains(loc.RSTPath, "3.4") {
		t.Errorf("want 3.4 location, got %s", loc.RSTPath)
	}
}

func TestBuild_MultipleLabelsSameHeading(t *testing.T) {
	root := t.TempDir()
	writeRST(t, root, "a.rst", `.. _first-alias:
.. _second-alias:

Shared Heading
==============
`)

	idx, err := Build(root)
	if err != nil {
		t.Fatal(err)
	}
	for _, label := range []string{"first-alias", "second-alias"} {
		loc, ok := idx.Resolve(label, "")
		if !ok {
			t.Errorf("%s did not resolve", label)
			continue
		}
		if loc.Heading != "Shared Heading" {
			t.Errorf("%s: want 'Shared Heading', got %q", label, loc.Heading)
		}
	}
}

func TestBuild_FlagsFirstHeadingAsPageTitle(t *testing.T) {
	root := t.TempDir()
	writeRST(t, root, "doc.rst", `.. _page-level-label:

Top of page
===========

Intro paragraph.

.. _section-label:

A subsection
------------
`)

	idx, err := Build(root)
	if err != nil {
		t.Fatal(err)
	}
	pageLevel, ok := idx.Resolve("page-level-label", "")
	if !ok || !pageLevel.IsPageTitle {
		t.Errorf("page-level-label IsPageTitle = %v (want true)", pageLevel.IsPageTitle)
	}
	section, ok := idx.Resolve("section-label", "")
	if !ok || section.IsPageTitle {
		t.Errorf("section-label IsPageTitle = %v (want false)", section.IsPageTitle)
	}
}

func TestBuild_UnknownLabelReturnsFalse(t *testing.T) {
	root := t.TempDir()
	writeRST(t, root, "a.rst", `Nothing to see here.
`)
	idx, err := Build(root)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := idx.Resolve("does-not-exist", ""); ok {
		t.Error("expected unknown label to return false")
	}
}

func writeRST(t *testing.T, root, rel, content string) {
	t.Helper()
	full := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestBuild_DottedLabels(t *testing.T) {
	// Canton-style autogenerated reference content uses dotted labels
	// like `.. _bootstrap.help:` extensively. Without dot support the
	// index drops ~45% of corpus labels.
	root := t.TempDir()
	writeRST(t, root, "console.rst", `.. _bootstrap.help:

Bootstrap Help
==============

Some content.

.. _topology.help:

Topology Help
-------------

More content.

.. _health.active:

Health Active
~~~~~~~~~~~~~

Even more content.
`)

	idx, err := Build(root)
	if err != nil {
		t.Fatalf("build: %v", err)
	}

	for _, label := range []string{"bootstrap.help", "topology.help", "health.active"} {
		loc, ok := idx.Resolve(label, "")
		if !ok {
			t.Errorf("expected dotted label %q to resolve", label)
			continue
		}
		if loc.Heading == "" {
			t.Errorf("dotted label %q resolved with empty heading", label)
		}
	}
}

func contains(haystack, needle string) bool {
	for i := 0; i+len(needle) <= len(haystack); i++ {
		if haystack[i:i+len(needle)] == needle {
			return true
		}
	}
	return false
}
