// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates.
// SPDX-License-Identifier: Apache-2.0

// Package labelindex walks an RST documentation tree and builds a map of
// RST cross-reference labels (the targets of `:ref:` and friends) to the
// file + heading they anchor.
//
// RST labels look like:
//
//	.. _canton-getting-started:
//
//	Getting Started
//	===============
//
// The label attaches to whatever immediately follows — usually a heading.
// For the migration we only care about label → heading because that's
// what gives the MDX reader a meaningful link target.
//
// The corpus has labels duplicated across version trees (canton/3.4 and
// canton/3.5 both define many of the same labels). Build stores all
// occurrences per label; resolution picks one using nearest-source
// heuristics — see (*Index).Resolve.
package labelindex

import (
	"bufio"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Location points at one definition of a label inside the source tree.
type Location struct {
	RSTPath string // absolute path to the source .rst file
	Heading string // text of the heading the label anchors
	Line    int    // 1-based line number of the label in the source
	// IsPageTitle is true when this label anchors the FIRST heading
	// in its source file — i.e. it's a page-level reference rather
	// than a section-level one. Callers use this to decide whether
	// to emit a `#fragment` on the link target. For page-level refs
	// the fragment is redundant: Mintlify auto-generates the page's
	// own title anchor, and the link already targets that page.
	IsPageTitle bool
}

// Index is a map from label name to every location that defines it.
// A label can legitimately appear in multiple files (e.g. the same
// conceptual label in canton/3.4 and canton/3.5). Resolve chooses a
// single location at query time based on the requesting source file.
type Index struct {
	labels map[string][]Location
}

// Build walks root for `.rst` files and extracts every `.. _label:`
// declaration plus the heading text immediately following it. The walk
// is single-pass and avoids loading entire files into memory.
func Build(root string) (*Index, error) {
	idx := &Index{labels: make(map[string][]Location)}
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".rst") {
			return nil
		}
		return idx.scan(path)
	})
	if err != nil {
		return nil, err
	}
	return idx, nil
}

var (
	// Labels may include `.`, `_`, and `-` after the first character.
	// `.` is common in autogenerated reference content like Canton's
	// console.rst, where labels look like `bootstrap.help`,
	// `topology.help`, or `health.active`. Without dot support the
	// index drops ~45% of labels in the corpus.
	reLabel = regexp.MustCompile(`^\.\.\s+_([A-Za-z0-9][A-Za-z0-9._\-]*):\s*$`)
	// A heading underline is a run of 3+ of =/-/~/^/" chars.
	reUnderline = regexp.MustCompile(`^[#+*=\-~^"]{3,}\s*$`)
)

func (i *Index) scan(path string) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 64*1024), 1024*1024)

	var pendingLabels []pendingLabel
	var prev string
	lineNum := 0
	seenHeading := false

	for scanner.Scan() {
		lineNum++
		line := scanner.Text()

		// Label declaration.
		if m := reLabel.FindStringSubmatch(line); m != nil {
			pendingLabels = append(pendingLabels, pendingLabel{name: m[1], line: lineNum})
			prev = line
			continue
		}

		// Heading detection: the current line is an underline, the
		// previous non-blank line was the title.
		if reUnderline.MatchString(line) && prev != "" && strings.TrimSpace(prev) != "" {
			heading := strings.TrimSpace(prev)
			isPageTitle := !seenHeading
			seenHeading = true
			for _, pl := range pendingLabels {
				i.labels[pl.name] = append(i.labels[pl.name], Location{
					RSTPath:     path,
					Heading:     heading,
					Line:        pl.line,
					IsPageTitle: isPageTitle,
				})
			}
			pendingLabels = nil
		}

		prev = line
	}
	return scanner.Err()
}

type pendingLabel struct {
	name string
	line int
}

// Resolve returns the best Location for the given label, relative to
// sourcePath. Heuristic: prefer definitions that share the longest path
// prefix with sourcePath (so a :ref: inside canton/3.5/... prefers a
// label defined inside canton/3.5/... over one in canton/3.4/...).
// Returns false if the label is not known.
func (i *Index) Resolve(label, sourcePath string) (Location, bool) {
	locs, ok := i.labels[label]
	if !ok || len(locs) == 0 {
		return Location{}, false
	}
	if len(locs) == 1 {
		return locs[0], true
	}
	best := 0
	bestScore := -1
	for idx, loc := range locs {
		score := sharedPrefixLen(sourcePath, loc.RSTPath)
		if score > bestScore {
			bestScore = score
			best = idx
		}
	}
	return locs[best], true
}

// sharedPrefixLen returns the number of leading path components that a
// and b have in common (after normalizing with filepath.Clean).
func sharedPrefixLen(a, b string) int {
	as := strings.Split(filepath.Clean(a), string(filepath.Separator))
	bs := strings.Split(filepath.Clean(b), string(filepath.Separator))
	n := 0
	for n < len(as) && n < len(bs) && as[n] == bs[n] {
		n++
	}
	return n
}

// Size returns the number of unique labels in the index. Callers use it
// to log the size of the corpus they're working against.
func (i *Index) Size() int { return len(i.labels) }

// TotalDefinitions returns the total number of label definitions across
// all files (including duplicates across version trees).
func (i *Index) TotalDefinitions() int {
	n := 0
	for _, v := range i.labels {
		n += len(v)
	}
	return n
}

// Labels returns a sorted list of every label name. Useful for
// debugging and for `--list-labels` CLI output.
func (i *Index) Labels() []string {
	out := make([]string, 0, len(i.labels))
	for k := range i.labels {
		out = append(out, k)
	}
	return out
}
